name: Setup Perl environment
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup fastq-multx
      uses: actions/checkout@v2
      with:
        repository: 'brwnj/fastq-multx'
        path: fastq-multx
        ref: 'v1.4.0'
    - run: |
        cd fastq-multx
        make
        cd ..
        mkdir -p $GITHUB_WORKSPACE/bin
        echo "::add-path::$GITHUB_WORKSPACE/bin"
        cp fastq-multx/fastq-multx $GITHUB_WORKSPACE/bin
        chmod +x $GITHUB_WORKSPACE/bin/fastq-multx
    - uses: actions/checkout@v2
    - name: Setup perl & install htseq2multx
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: '5.18'
    - run: |
        cpanm --installdeps --notest .
        cd tests
        ./run_tests.sh
