name: Setup Perl environment

on: [push]

uses: shogo82148/actions-setup-perl@v1.6.0
with:
  perl-version: '5.18'

jobs:
  build:
    steps:
    - uses: actions/checkout@v2
    - uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: '5.18'
    - run: |
        cpanm --installdeps --notest .
        cd tests
        ./run_tests.sh
