name: Setup Perl environment

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout fastq-multx
    - uses: actions/checkout@v2
      with:
        repository: 'brwnj/fastq-multx'
        path: fastq-multx
        ref: 'v1.4.0'
    - run: |
        cd fastq-multx
        make
        echo "::add-path::./fastq-multx"
        cd ..

    - name: htseq2multx build & test
    - uses: actions/checkout@v2
    - uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: '5.18'
    - run: |
        cpanm --installdeps --notest .
        cd tests
        ./run_tests.sh
