name: Setup Perl environment
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout fastq-multx
      uses: actions/checkout@v2
      with:
        repository: 'brwnj/fastq-multx'
        path: fastq-multx
        ref: 'v1.4.0'
    - name: Install fastq-multx
      run: |
        cd fastq-multx
        make
        chmod +x fastq-multx
        echo "::add-path::${GITHUB_WORKSPACE}/fastq-multx"
    - name: Setup perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: '5.32'
    - name: Checkout htseq2multx
      uses: actions/checkout@v2
      with:
          path: htseq2multx
    - name: Install htseq2multx dependencies
      run: |
        cd htseq2multx
        cpanm --installdeps --notest .
    - name: Install htseq2multx
      run: |
        cd htseq2multx
        perl Makefile.PL
        make
        make install
    - name: Test htseq2multx
      run: |
        cd htseq2multx/tests
        ./run_tests.sh
