name: Setup Perl environment
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: htseq2multx & fastq-multx build & test
    - uses: actions/checkout@v2
      with:
        repository: 'brwnj/fastq-multx'
        path: fastq-multx
        ref: 'v1.4.0'
    - run: |
        cd fastq-multx
        make
        echo "::add-path::./fastq-multx"
        cd ..
    - uses: actions/checkout@v2
    - uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: '5.18'
    - run: |
        cpanm --installdeps --notest .
        cd tests
        ./run_tests.sh
